install.packages(c("raster", "dplyr", "spData", "spDataLarge", "sf"))
install.packages(c("leaflet", "shiny"))
install.packages("readxl")
install.packages("htmlwidgets")
install.packages("magick")
install.packages("here")
install.packages("tmap")
install.packages("ggplot2")
install.packages("gifski")
#Convocação dos pacotes#
library(dplyr)
library(spData)
library(spDataLarge)
library(tmap)
library(readxl)
library(htmlwidgets)
library(magick)
library(here)
library(leaflet) 
library(ggplot2) 
library(shiny)   
library(sf)
library(raster)
library(gifski)